### ISSUE TITLE
Build failing 

### ISSUE THREAD

**Issue by maireadmccabe** [automationeverywhere/soapui-groovy-maven#2]
Getting the following output when trying to build from master
`>mvn clean install
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building soapui-groovy-maven project 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://www.soapui.org/repository/maven2/com/smartbear/soapui/soapui-maven-plugin/5.3.0/soapui-maven-plugin-5.3.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.057 s
[INFO] Finished at: 2018-10-11T17:02:34+01:00
[INFO] Final Memory: 11M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin com.smartbear.soapui:soapui-maven-plugin:5.3.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.smartbear.soapui:soapui-maven-plugin:jar:5.3.0: Could not transfer
artifact com.smartbear.soapui:soapui-maven-plugin:pom:5.3.0 from/to smartbear-sweden-plugin-repository (http://www.soapui.org/repository/maven2/): Connect to www.soapui.org:80 [www.soapui.org/50.57.35.134] failed: Connecti
on timed out: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
`

**Comment by automationeverywhere** [comment]
I am not seeing any such errors. Please check if you are able to access the repository mentioned in the pom.xml.

**Comment by maireadmccabe** [comment]
Yeah that's the issue, I can't reach that repo on my network. Thanks.
